name: habit_tracker
description: A beautiful habit tracking app with reminders and analytics

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Notifications (simplified for now)
  # flutter_local_notifications: ^17.2.3
  # permission_handler: ^11.1.0
  # timezone: ^0.9.2
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  
  # Date/Time handling
  intl: ^0.19.0
  
  # Charts for statistics
  fl_chart: ^0.66.0
  
  # Icons
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
